-- Create table for Google Merchant Center products
CREATE TABLE IF NOT EXISTS gmc_products (
    id TEXT PRIMARY KEY, -- The REST ID of the product
    offer_id TEXT, -- The user-provided offer ID
    title TEXT,
    description TEXT,
    link TEXT,
    image_link TEXT,
    price_value NUMERIC,
    price_currency TEXT,
    availability TEXT,
    brand TEXT,
    google_product_category TEXT,
    product_types TEXT[], -- Array of product types
    channel TEXT,
    content_language TEXT,
    target_country TEXT,
    feed_label TEXT,
    
    -- Status fields
    status TEXT, -- 'active', 'expiring', 'pending', 'disapproved'
    item_level_issues JSONB, -- Store detailed issues as JSON
    
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    synced_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create table for Google Merchant Center performance metrics (daily)
CREATE TABLE IF NOT EXISTS gmc_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    
    -- Dimensions
    offer_id TEXT, -- Optional, if we break down by product
    brand TEXT,
    category_l1 TEXT,
    product_type_l1 TEXT,
    
    -- Metrics
    clicks INTEGER DEFAULT 0,
    impressions INTEGER DEFAULT 0,
    ctr NUMERIC DEFAULT 0,
    conversions NUMERIC DEFAULT 0,
    conversion_value NUMERIC DEFAULT 0,
    
    synced_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    UNIQUE(date, offer_id) -- Ensure unique record per product per day (or just date if offer_id is null for aggregate)
);

-- Create table for sync logs
CREATE TABLE IF NOT EXISTS gmc_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_completed_at TIMESTAMP WITH TIME ZONE,
    status TEXT, -- 'running', 'success', 'partial', 'failed'
    records_synced INTEGER DEFAULT 0,
    errors TEXT[]
);

-- Enable RLS but allow service role full access (default behavior usually, but good to be explicit if we were adding policies)
ALTER TABLE gmc_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE gmc_performance ENABLE ROW LEVEL SECURITY;
ALTER TABLE gmc_sync_log ENABLE ROW LEVEL SECURITY;

-- Create policies to allow read access to authenticated users (dashboard viewers)
CREATE POLICY "Allow read access to authenticated users for gmc_products"
ON gmc_products FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow read access to authenticated users for gmc_performance"
ON gmc_performance FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow read access to authenticated users for gmc_sync_log"
ON gmc_sync_log FOR SELECT TO authenticated USING (true);
